# This is a basic workflow to help you get started with Actions

name: branch hooks

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on: [push, pull_request]
    
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Branch name
        run: |
            git log
            git status
            echo running on branch ${GITHUB_REF##*/}
